# Copyright (c) 2016, Linaro Limited
# All rights reserved.
# SPDX-License-Identifier:     BSD-3-Clause
#
# Please update xxxx for your coverity token and notification email if required
# pushing to github/master will run make check
# pushing to github/coverity_scan will also launch a static analysis
# See https://scan.coverity.com/travis_ci

language: c
sudo: required
dist: trusty
group: deprecated-2017Q2
env:
  global:
    # COVERITY_SCAN_TOKEN
    # ** specific to your project **
    # Note:
    # You should have a github account and travis linked travis account.
    # The secure key to be filled below is the 685 character long encrypted
    # token you can find as follow from your coverity dashboard
    # (at https://scan.coverity.com/dashboard):
    # Click on the github project (<you>/odp)
    # Click on "submit build"
    # Click on "Configure Travis CI"
    # Look at the COVERITY_SCAN_TOKEN in the env: global: section
    # of the configuration example.
    # copy the secure:<key> below
    #
    - secure: "xxxx"
    #
    # By default Linaro CODECOV_TOKEN token is used. It's ok to use it to see
    # for individual commit validation. But you you want to track tests history
    # you need generated new one at https://codecov.io specific for your repo.
    - CODECOV_TOKEN=8e1c0fd8-62ff-411e-a79f-5839f6662c11

addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - gcc
                        - clang-3.8
                        - automake autoconf libtool libssl-dev graphviz mscgen doxygen
                        - libpcap-dev
                        - libconfig-dev
#        coverity_scan:
#                project:
#                        name: "$TRAVIS_REPO_SLUG"
#                        notification_email: xxxx
#                        build_command_prepend: "./bootstrap && ./configure --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example"
#                        build_command:   "make"
#                        branch_pattern: coverity_scan

compiler:
        - gcc
        - clang-3.8

cache:
        ccache: true
        pip: true
        directories:
                - dpdk
                - netmap
                - $HOME/cunit-install

env:
        - CONF=""
        - CONF="--disable-abi-compat"
        - CONF="--enable-schedule-sp"
        - CONF="--enable-schedule-iquery"
        - CONF="--enable-schedule-scalable"
        - CONF="--enable-dpdk-zero-copy"

before_install:

        # Install cross toolchains, etc
        # apt-get update may fail thanks to Ubuntu removing Packages/indices while not removing relevant parts of Release file
        - if [ -n "$CROSS_ARCH" ] ;
          then
                  BUILD_GNU_TYPE=`dpkg-architecture -a"$CROSS_ARCH" -qDEB_BUILD_GNU_TYPE` ;
                  CROSS_GNU_TYPE=`dpkg-architecture -a"$CROSS_ARCH" -qDEB_HOST_GNU_TYPE` ;
                  CROSS_MULTIARCH=`dpkg-architecture -a"$CROSS_ARCH" -qDEB_HOST_MULTIARCH` ;
                  CROSS="--host="$CROSS_GNU_TYPE" --build="$BUILD_GNU_TYPE" --prefix=/usr --includedir=/usr/include/"$CROSS_MULTIARCH" --libdir=/usr/lib/"$CROSS_MULTIARCH" --libexecdir=/usr/lib/"$CROSS_MULTIARCH"" ;
                  sudo dpkg --add-architecture "$CROSS_ARCH" ;
                  sudo -E apt-add-repository -y "deb http://ports.ubuntu.com trusty main" ;
                  sudo -E apt-add-repository -y "deb http://ports.ubuntu.com trusty-updates main" ;
                  sudo -E apt-get -y update || true ;
                  sudo -E apt-get -y --no-install-suggests --no-install-recommends --force-yes install build-essential gcc-"$CROSS_GNU_TYPE" pkg-config-"$CROSS_GNU_TYPE" ;
                  sudo -E apt-get -y --no-install-suggests --no-install-recommends --force-yes install libc6-dev:"$CROSS_ARCH" libconfig-dev:"$CROSS_ARCH" libssl-dev:"$CROSS_ARCH" zlib1g-dev:"$CROSS_ARCH" libconfig-dev:"$CROSS_ARCH" ;
          fi
        - if test ! -L /usr/lib/ccache/${CC%% *} ; then sudo ln -s -t /usr/lib/ccache/ `which ${CC%% *}` ; fi
        - ccache -s
        # Install cunit for the validation tests because distro version is too old and fails C99 compile
        - sudo apt-get remove libcunit1-dev libcunit1
        - export LD_LIBRARY_PATH="$HOME/cunit-install/$CROSS_ARCH/lib:$LD_LIBRARY_PATH"
        - |
          if [ ! -f "$HOME/cunit-install/$CROSS_ARCH/lib/libcunit.a" ]; then
            export CUNIT_VERSION=2.1-3
            curl -sSOL https://github.com/Linaro/libcunit/releases/download/${CUNIT_VERSION}/CUnit-${CUNIT_VERSION}.tar.bz2
            tar -jxf *.bz2
            pushd CUnit*
            libtoolize --force --copy
            aclocal
            autoheader
            automake --add-missing --include-deps --copy
            autoconf
            ./configure --prefix=$HOME/cunit-install/$CROSS_ARCH --enable-debug --enable-automated --enable-basic --enable-console --enable-examples --enable-test $CROSS || cat config.log
            make
            sudo make install
            popd
          fi
        - find $HOME/cunit-install

install:
        - echo 1000 | sudo tee /proc/sys/vm/nr_hugepages
        - sudo mkdir -p /mnt/huge
        - sudo mount -t hugetlbfs nodev /mnt/huge

        - sudo apt-get -qq update
        - sudo apt-get install linux-headers-`uname -r`
        - sudo pip install coverage
        - gem install asciidoctor
        - PATH=${PATH//:\.\/node_modules\/\.bin/}

#	DPDK pktio. Note that cache must be purged if dpdk version changes.
        - TARGET=${TARGET:-"x86_64-native-linuxapp-gcc"}
        - |
          if [ ! -f "dpdk/${TARGET}/lib/libdpdk.a" ]; then
            git -c advice.detachedHead=false clone -q --depth=1 --single-branch --branch=v17.02 http://dpdk.org/git/dpdk dpdk
            pushd dpdk
            git log --oneline --decorate
            make config T=${TARGET} O=${TARGET}
            pushd ${TARGET}
            sed -ri 's,(CONFIG_RTE_LIBRTE_PMD_PCAP=).*,\1y,' .config
            sed -ri 's,(CONFIG_RTE_LIBRTE_PMD_OPENSSL=).*,\1y,' .config
            popd
            make install T=${TARGET} EXTRA_CFLAGS="-fPIC"
            rm -r ./doc ./${TARGET}/app ./${TARGET}/build
            popd
          fi

#	Netmap pktio
        - |
          if [ ! -f "netmap/LINUX/netmap.ko" ]; then
            git -c advice.detachedHead=false clone -q --depth=1 --single-branch --branch=v11.2 https://github.com/luigirizzo/netmap.git
            pushd netmap/LINUX
            ./configure
            make
            sudo insmod ./netmap.ko
            popd
          fi

script:
        - ./bootstrap
        - ./configure --prefix=$HOME/odp-install  --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example --with-dpdk-path=`pwd`/dpdk/${TARGET} --with-netmap-path=`pwd`/netmap --with-cunit-path=$HOME/cunit-install/$CROSS_ARCH $CONF
        - make -j $(nproc)
        - mkdir /dev/shm/odp
        - sudo LD_LIBRARY_PATH="$HOME/cunit-install/$CROSS_ARCH/lib:$LD_LIBRARY_PATH" ODP_SHM_DIR=/dev/shm/odp make check
        - make install

        - echo "Checking linking and run from install..."
        - pushd $HOME
        - echo "Dynamic link.."
        - ${CC} ${OLDPWD}/example/hello/odp_hello.c -o odp_hello_inst `PKG_CONFIG_PATH=${HOME}/odp-install/lib/pkgconfig pkg-config --cflags --libs libodp-linux,libodp-modules`
        - LD_LIBRARY_PATH="${HOME}/odp-install/lib:$LD_LIBRARY_PATH" ./odp_hello_inst
        - echo "Static link.."
        - ${CC} ${OLDPWD}/example/hello/odp_hello.c -o odp_hello_inst `PKG_CONFIG_PATH=${HOME}/odp-install/lib/pkgconfig pkg-config --cflags --libs libodp-modules,libodp-linux --static` -static
        - ./odp_hello_inst
        - ccache -s

jobs:
        include:
                - stage: test
                  compiler: aarch64-linux-gnu-gcc
                  env: TEST="aarch64-linux-gnu" CROSS_ARCH="arm64"
                  install: true
                  script:
                          - ./bootstrap
                          - ./configure --prefix=$HOME/odp-install $CROSS
                            --disable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-test-perf-proc --enable-test-example --with-cunit-path=$HOME/cunit-install/$CROSS_ARCH
                          - make -j $(nproc)
                - stage: test
                  compiler: "\"clang-3.8 --target=aarch64-linux-gnu\""
                  env: TEST="clang-3.8 aarch64-linux-gnu" CROSS_ARCH="arm64"
                  install: true
                  script:
                          - ./bootstrap
                          - ./configure --prefix=$HOME/odp/odp-install $CROSS
                            --disable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-test-perf-proc --enable-test-example --with-cunit-path=$HOME/cunit-install/$CROSS_ARCH
                          - make -j $(nproc)
                - stage: test
                  compiler: arm-linux-gnueabihf-gcc
                  env: TEST="arm-linux-gnueabihf" CROSS_ARCH="armhf"
                  install: true
                  script:
                          - ./bootstrap
                          - ./configure --prefix=$HOME/odp-install $CROSS
                            --disable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-test-perf-proc --enable-test-example --with-cunit-path=$HOME/cunit-install/$CROSS_ARCH
                          - make -j $(nproc)
                - stage: test
                  compiler: "\"clang-3.8 --target=arm-linux-gnueabihf\""
                  env: TEST="clang-3.8 arm-linux-gnueabihf" CROSS_ARCH="armhf" CFLAGS="-march=armv7-a"
                  install: true
                  script:
                          - ./bootstrap
                          - ./configure --prefix=$HOME/odp-install $CROSS
                            --disable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-test-perf-proc --enable-test-example --with-cunit-path=$HOME/cunit-install/$CROSS_ARCH
                          - make -j $(nproc)
                - stage: test
                  compiler: powerpc-linux-gnu-gcc
                  env: TEST="powerpc-linux-gnueabihf" CROSS_ARCH="powerpc"
                  install: true
                  script:
                          - ./bootstrap
                          - ./configure --prefix=$HOME/odp-install $CROSS
                            --disable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-test-perf-proc --enable-test-example --with-cunit-path=$HOME/cunit-install/$CROSS_ARCH
                          - make -j $(nproc)
                - stage: test
                  compiler: "\"clang-3.8 --target=powerpc-linux-gnu\""
                  env: TEST="clang-3.8 powerpc-linux-gnu" CROSS_ARCH="powerpc"
                  install: true
                  script:
                          - ./bootstrap
                          - ./configure --prefix=$HOME/odp-install $CROSS
                            --disable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-test-perf-proc --enable-test-example --with-cunit-path=$HOME/cunit-install/$CROSS_ARCH
                          - make -j $(nproc)
                - stage: test
                  env: TEST=coverage
                  compiler: gcc
                  script:
                          - ./bootstrap
                          - ./configure --prefix=$HOME/odp-install --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example --with-dpdk-path=`pwd`/dpdk/${TARGET} --with-netmap-path=`pwd`/netmap CFLAGS="-O0 -coverage" --with-cunit-path=$HOME/cunit-install/$CROSS_ARCH CXXFLAGS="-O0 -coverage" LDFLAGS="--coverage"
                          - sudo LD_LIBRARY_PATH="$HOME/cunit-install/$CROSS_ARCH/lib:$LD_LIBRARY_PATH" PATH=${PATH//:\.\/node_modules\/\.bin/} make check
                          - find . -type f -iname '*.[ch]' -not -path ".git/*" -execdir gcov {} \; ; bash <(curl -s https://codecov.io/bash) -X coveragepy
                - stage: test
                  env: TEST=distcheck
                  compiler: gcc
                  script:
                          - ./bootstrap
                          - ./configure --prefix=$HOME/odp-install --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example --with-cunit-path=$HOME/cunit-install/$CROSS_ARCH
                          - sudo PATH="$PATH" LD_LIBRARY_PATH="$HOME/cunit-install/$CROSS_ARCH/lib:$LD_LIBRARY_PATH" make distcheck CFLAGS="-I$HOME/cunit-install/$CROSS_ARCH/include" LDFLAGS="-L$HOME/cunit-install/$CROSS_ARCH/lib"
                - stage: test
                  env: TEST=doxygen
                  compiler: gcc
                  script:
                          # doxygen does not trap on warnings, check for them here.
                          - ./bootstrap
                          - ./configure
                          - make doxygen-doc |tee doxygen.log
                          - fgrep -rvq warning ./doxygen.log
                - stage: test
                  env: TEST=checkpatch
                  compiler: gcc
                  script:
                          - echo ${TRAVIS_COMMIT_RANGE};
                          - ODP_PATCHES=`echo ${TRAVIS_COMMIT_RANGE} | sed 's/\.//'`;
                          - if [ -z "${ODP_PATCHES}" ]; then env; exit 1; fi;
                          - ./scripts/ci-checkpatches.sh ${ODP_PATCHES};
                - stage: test
                  env: TEST=linux-dpdk
                  compiler: gcc
                  script:
                          - ./bootstrap
                          - ./configure --with-platform=linux-dpdk --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example --with-sdk-install-path=`pwd`/dpdk/${TARGET} --with-cunit-path=$HOME/cunit-install/$CROSS_ARCH $CONF
                          - make -j $(nproc)
                          - sudo LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" make check
after_failure:
  - cat config.log
  - find . -name 'test-suite.log' -execdir grep -il "FAILED" {} \; -exec echo {} \; -exec cat {} \;
